domains:
  - name: www.example.com
  - name: www.github.com
  - name: www.microsoft.com
  - name: www.apple.com
  - name: www.exampledomain.com
expire_threshold_days: 90
cleanup_days: 7
cleanup_enabled: true
alert_channels:
  email:
    enabled: true
    smtp_host: smtp.example.com
    smtp_port: 587
    from: alerts@example.com
    to: team@example.com
    send_email: true
